# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib fastjmespath, .registration = TRUE
NULL

#' A compiled JMESPath expression.
#'
#' Compile once with `jmespath_compile()` and reuse for many searches.
#' @noRd
#'
JmesExpr <- new.env(parent = emptyenv())

JmesExpr$new <- function(expr) .Call(wrap__JmesExpr__new, expr)

JmesExpr$expression <- function() .Call(wrap__JmesExpr__expression, self)

JmesExpr$search <- function(data, simplify) .Call(wrap__JmesExpr__search, self, data, simplify)

JmesExpr$search_json <- function(json, simplify) .Call(wrap__JmesExpr__search_json, self, json, simplify)

#' @export
`$.JmesExpr` <- function (self, name) { func <- JmesExpr[[name]]; environment(func) <- environment(); func }

#' @export
`[[.JmesExpr` <- `$.JmesExpr`

# nolint end
